### ISSUE TITLE
can't install on mac os x

### ISSUE THREAD

**Issue by cosnis** [manahl/arctic#14]
```
clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/_compress.c -o build/temp.macosx-10.10-x86_64-2.7/src/_compress.o -fopenmp
src/_compress.c:259:10: fatal error: 'omp.h' file not found
#include "omp.h"
         ^
1 error generated.
error: command 'clang' failed with exit status 1
```

i installed clang-omp..

**Comment by AdrianTeng** [comment]
@jamesblackburn reported [this issue](https://github.com/Homebrew/homebrew/issues/40391) to homebrew. In the mean time please use gcc, instructions [here](http://stackoverflow.com/questions/28546288/omp-h-not-found-os-x-yosemite-not-using-newest-gcc-version)

**Comment by jamesblackburn** [comment]
This will be quite painful for OS X users (of which I'm one), I think we need to produce a .egg with the cython bits in to make this easier

**Comment by mphilipose** [comment]
I ran into the same problem.
I solved it by running "brew install clang-omp"

Hope this helps!

**Comment by jamesblackburn** [comment]
@mphilipose brew's clang-omp didn't work for me: https://github.com/Homebrew/homebrew/issues/40391 gcc in conda works though...

**Comment by cosnis** [comment]
is that work now?

**Comment by llazzaro** [comment]
here is working on OS X

**Comment by canada4663** [comment]
Here is what I did to get this working in El Capitan:

````
brew remove libivmp
brew install libiomp
brew install gcc --without-multilib
brew link gcc
CC=/usr/local/bin/gcc-5 pip install git+https://github.com/manahl/arctic.git
````

I think the key was installing v.5.x of gcc from home-brew, not Apple's command line tool version without multilib support, then ensuring that I pointed to that compiler when installing via pip.

**Comment by femtotrader** [comment]
+1 it works with my Mac too (OS X Yosemite 10.10.5)

**Comment by femtotrader** [comment]
I wonder how to install a locally modified version of Arctic under OS X

    CC=/usr/local/bin/gcc-5 sudo python setup.py install

raises

```
gcc -fno-strict-aliasing -I//anaconda/envs/py27/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda/envs/py2/include/python2.7 -c src/_compress.c -o build/temp.macosx-10.5-x86_64-2.7/src/_compress.o -fopenmp
src/_compress.c:244:10: fatal error: 'omp.h' file not found
#include "omp.h"
         ^
1 error generated.
error: command 'gcc' failed with exit status 1
```

**Comment by jamesblackburn** [comment]
You can build it in a conda environment (having installed the conda GCC).  When it comes to the Python link line, if you run that with `-static` when linking against OMP, then the egg seems to be portable.

**Comment by spyamine** [comment]
worked for me in El Capitan.

Thanks canada4663

**Comment by TomTaylorLondon** [comment]
@femtotrader the exception is because osx gcc (which is just a symlink to clang) doesn't ship with openmp support out of the box. You can install gcc with openmp and compile using the steps canada4663 highlighted

```
brew install gcc --without-multilib
brew link gcc
CC=/usr/local/bin/gcc-5 pip install git+https://github.com/manahl/arctic.git
```

**Comment by huaiweicheng** [comment]
EI Capitan. The last step does not work. 
    /usr/local/bin/gcc-5 -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/_compress.c -o build/temp.macosx-10.11-intel-2.7/src/_compress.o -fopenmp
    gcc-5: error: unrecognized command line option '-Wshorten-64-to-32'
    error: command '/usr/local/bin/gcc-5' failed with exit status 1

u guys deal with this problem?
Many thanks.

**Comment by bmoscon** [comment]
@huaiweicheng its possible your version of GCC just doesn't support that flag. Its just a flag to enable a very specific type of warning. You can just remove it from the command and try again.

**Comment by rudolf-bauer** [comment]
I think `-Wshorten-64-to-32` is a clang specific flag and unsupported by gcc as stated here: [https://stackoverflow.com/questions/1759807/c-warns-about-implicit-long-to-int-conversion](https://stackoverflow.com/questions/1759807/c-warns-about-implicit-long-to-int-conversion).

However, I have managed to install arctic with clang. As proposed by @cosnis and @mphilipose I installed iomp for clang: 

`brew install clang-omp libiomp`

Further, I manually specified the `clang-omp` compiler and the `libiomp` paths to use in the `setup.py` script. Note that you might need to replace `20150701` by the libiomp version installed on your system.

`CC="clang-omp -I/usr/local/Cellar/libiomp/20150701/include/libiomp/ -L/usr/local/Cellar/libiomp/20150701/lib" pip install git+https://github.com/manahl/arctic.git`

 This worked fine for me. By the way: I'm working an OSX El Capitan.

**Comment by nekopuni** [comment]
@rudolf-bauer this worked for me as well with Yosemite. Thank you.

**Comment by rthford** [comment]
Hi - having some issues with the above installing on mac sierra

Tried using gcc and the work around shown above, but getting the following error:

  /usr/local/Cellar/gcc/6.2.0 -fno-strict-aliasing -I/Users/local/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/local/anaconda/include/python2.7 -c src/_compress.c -o build/temp.macosx-10.6-x86_64-2.7/src/_compress.o -fopenmp

    unable to execute '/usr/local/Cellar/gcc/6.2.0': Permission denied
    error: command '/usr/local/Cellar/gcc/6.2.0' failed with exit status 1

**Comment by HedgeShot** [comment]
Hi,

Just tried to install Arctic on a fresh El Capitan install. I had to tweak a bit the proposition of @rudolf-bauer. 

1. clang-omp is now in the boneyard directory of homebrew.
`
brew install homebrew/boneyard/clang-omp
`
2. Got a new error about "stdio.h" that was missing. So I had to install the Xcode command line tool
`
xcode-select --install
`
and follow the command prompt.

The install went smoothly after that. 
Hope this helps.

**Comment by anthonywittemann** [comment]
For those of you on Mac Sierra 10.12.1, modifying the last line of @canada4663 solution to
```CC=/usr/local/bin/gcc-6` pip3 install git+https://github.com/manahl/arctic.git```
did the trick for me

**Comment by bmoscon** [comment]
OSX build now works. Must have gcc 6 installed. Install like so:

```
brew install gcc --without-multilib
```


Not ideal, but you should only have to install gcc/g++ with brew to get the build to work. No more weird env variables need to be set.
